host: https://api.github.com
oauth: oauth_token_here
merged organization: org
merged repository: merge-test
repositories:
  - url: https://github.com/amaltson/github-merge.git
    sub directory: github-merge
  - url: https://github.com/amaltson/github-merge.git
    sub directory: github
