host: https://api.github.com
oauth: oauth_token_here
merged organization: org
merged repository: merge-test
repositories:
  - url: file:///tmp/repo1
    sub directory: github-merge
  - url: file:///tmp/repo2
    sub directory: github
